server:
  port: 9009


#??? ???????? ?? ??
spring:
  application:
    name: discoveryservice

#??? ??

#--????? ??
#-- ??? ??? ???? ???? ???? ( ???? ?? ?? )
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false